const users = [{
    "id": 1,
    "first_name": "Harley",
    "last_name": "Minget",
    "email": "hminget0@telegraph.co.uk",
    "gender": "Female"
  }, {
    "id": 2,
    "first_name": "Wenda",
    "last_name": "Cluckie",
    "email": "wcluckie1@google.ru",
    "gender": "Female"
  }, {
    "id": 3,
    "first_name": "Emlyn",
    "last_name": "Summergill",
    "email": "esummergill2@utexas.edu",
    "gender": "Female"
  }, {
    "id": 4,
    "first_name": "Vito",
    "last_name": "Ketts",
    "email": "vketts3@bravesites.com",
    "gender": "Male"
  }, {
    "id": 5,
    "first_name": "Sissy",
    "last_name": "Scotson",
    "email": "sscotson4@nhs.uk",
    "gender": "Female"
  }, {
    "id": 6,
    "first_name": "Euell",
    "last_name": "Botfield",
    "email": "ebotfield5@hubpages.com",
    "gender": "Male"
  }, {
    "id": 7,
    "first_name": "Bartie",
    "last_name": "Ramelot",
    "email": "bramelot6@nifty.com",
    "gender": "Male"
  }, {
    "id": 8,
    "first_name": "Consolata",
    "last_name": "Paradyce",
    "email": "cparadyce7@google.pl",
    "gender": "Female"
  }, {
    "id": 9,
    "first_name": "Zonda",
    "last_name": "Blackaller",
    "email": "zblackaller8@google.co.jp",
    "gender": "Female"
  }, {
    "id": 10,
    "first_name": "Chadd",
    "last_name": "D'Alesio",
    "email": "cdalesio9@printfriendly.com",
    "gender": "Male"
  }
]
  
module.exports = users